// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: tour_service.proto

package tour

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_DRAFT     Status = 0
	Status_PUBLISHED Status = 1
	Status_ARCHIVED  Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "DRAFT",
		1: "PUBLISHED",
		2: "ARCHIVED",
	}
	Status_value = map[string]int32{
		"DRAFT":     0,
		"PUBLISHED": 1,
		"ARCHIVED":  2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tour_service_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_tour_service_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{0}
}

type Difficult int32

const (
	Difficult_EASY   Difficult = 0
	Difficult_MEDIUM Difficult = 1
	Difficult_HARD   Difficult = 2
)

// Enum value maps for Difficult.
var (
	Difficult_name = map[int32]string{
		0: "EASY",
		1: "MEDIUM",
		2: "HARD",
	}
	Difficult_value = map[string]int32{
		"EASY":   0,
		"MEDIUM": 1,
		"HARD":   2,
	}
)

func (x Difficult) Enum() *Difficult {
	p := new(Difficult)
	*p = x
	return p
}

func (x Difficult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Difficult) Descriptor() protoreflect.EnumDescriptor {
	return file_tour_service_proto_enumTypes[1].Descriptor()
}

func (Difficult) Type() protoreflect.EnumType {
	return &file_tour_service_proto_enumTypes[1]
}

func (x Difficult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Difficult.Descriptor instead.
func (Difficult) EnumDescriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{1}
}

type TravelMethod int32

const (
	TravelMethod_CAR     TravelMethod = 0
	TravelMethod_BICYCLE TravelMethod = 1
	TravelMethod_WALKING TravelMethod = 2
)

// Enum value maps for TravelMethod.
var (
	TravelMethod_name = map[int32]string{
		0: "CAR",
		1: "BICYCLE",
		2: "WALKING",
	}
	TravelMethod_value = map[string]int32{
		"CAR":     0,
		"BICYCLE": 1,
		"WALKING": 2,
	}
)

func (x TravelMethod) Enum() *TravelMethod {
	p := new(TravelMethod)
	*p = x
	return p
}

func (x TravelMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TravelMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_tour_service_proto_enumTypes[2].Descriptor()
}

func (TravelMethod) Type() protoreflect.EnumType {
	return &file_tour_service_proto_enumTypes[2]
}

func (x TravelMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TravelMethod.Descriptor instead.
func (TravelMethod) EnumDescriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{2}
}

type TourDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  int64                     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId            int64                     `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Name                string                    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficult           Difficult                 `protobuf:"varint,5,opt,name=difficult,proto3,enum=Difficult" json:"difficult,omitempty"`
	Status              Status                    `protobuf:"varint,6,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	Price               float32                   `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	Tags                string                    `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"`
	Distance            float32                   `protobuf:"fixed32,9,opt,name=distance,proto3" json:"distance,omitempty"`
	Checkpoints         []*CheckpointDto          `protobuf:"bytes,10,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	PublishTime         *timestamppb.Timestamp    `protobuf:"bytes,11,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	ArchiveTime         *timestamppb.Timestamp    `protobuf:"bytes,12,opt,name=archive_time,json=archiveTime,proto3" json:"archive_time,omitempty"`
	Equipments          []*EquipmentDto           `protobuf:"bytes,13,rep,name=equipments,proto3" json:"equipments,omitempty"`
	TravelTimeAndMethod []*TravelTimeAndMethodDto `protobuf:"bytes,14,rep,name=travel_time_and_method,json=travelTimeAndMethod,proto3" json:"travel_time_and_method,omitempty"`
}

func (x *TourDto) Reset() {
	*x = TourDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TourDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourDto) ProtoMessage() {}

func (x *TourDto) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourDto.ProtoReflect.Descriptor instead.
func (*TourDto) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{0}
}

func (x *TourDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourDto) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *TourDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourDto) GetDifficult() Difficult {
	if x != nil {
		return x.Difficult
	}
	return Difficult_EASY
}

func (x *TourDto) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_DRAFT
}

func (x *TourDto) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourDto) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *TourDto) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TourDto) GetCheckpoints() []*CheckpointDto {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

func (x *TourDto) GetPublishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishTime
	}
	return nil
}

func (x *TourDto) GetArchiveTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchiveTime
	}
	return nil
}

func (x *TourDto) GetEquipments() []*EquipmentDto {
	if x != nil {
		return x.Equipments
	}
	return nil
}

func (x *TourDto) GetTravelTimeAndMethod() []*TravelTimeAndMethodDto {
	if x != nil {
		return x.TravelTimeAndMethod
	}
	return nil
}

type CheckpointDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PictureUrl  string  `protobuf:"bytes,4,opt,name=picture_url,json=pictureUrl,proto3" json:"picture_url,omitempty"`
	Latitude    float64 `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude   float64 `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	TourId      int64   `protobuf:"varint,7,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
}

func (x *CheckpointDto) Reset() {
	*x = CheckpointDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckpointDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointDto) ProtoMessage() {}

func (x *CheckpointDto) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointDto.ProtoReflect.Descriptor instead.
func (*CheckpointDto) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckpointDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CheckpointDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckpointDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CheckpointDto) GetPictureUrl() string {
	if x != nil {
		return x.PictureUrl
	}
	return ""
}

func (x *CheckpointDto) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CheckpointDto) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CheckpointDto) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type EquipmentDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *EquipmentDto) Reset() {
	*x = EquipmentDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentDto) ProtoMessage() {}

func (x *EquipmentDto) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentDto.ProtoReflect.Descriptor instead.
func (*EquipmentDto) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{2}
}

func (x *EquipmentDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EquipmentDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EquipmentDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TravelTimeAndMethodDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TravelTime   int64        `protobuf:"varint,1,opt,name=travel_time,json=travelTime,proto3" json:"travel_time,omitempty"`
	TravelMethod TravelMethod `protobuf:"varint,2,opt,name=travel_method,json=travelMethod,proto3,enum=TravelMethod" json:"travel_method,omitempty"`
}

func (x *TravelTimeAndMethodDto) Reset() {
	*x = TravelTimeAndMethodDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TravelTimeAndMethodDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelTimeAndMethodDto) ProtoMessage() {}

func (x *TravelTimeAndMethodDto) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelTimeAndMethodDto.ProtoReflect.Descriptor instead.
func (*TravelTimeAndMethodDto) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{3}
}

func (x *TravelTimeAndMethodDto) GetTravelTime() int64 {
	if x != nil {
		return x.TravelTime
	}
	return 0
}

func (x *TravelTimeAndMethodDto) GetTravelMethod() TravelMethod {
	if x != nil {
		return x.TravelMethod
	}
	return TravelMethod_CAR
}

type FindTourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindTourRequest) Reset() {
	*x = FindTourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTourRequest) ProtoMessage() {}

func (x *FindTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTourRequest.ProtoReflect.Descriptor instead.
func (*FindTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{4}
}

func (x *FindTourRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindByAuthorIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorId int64 `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *FindByAuthorIdRequest) Reset() {
	*x = FindByAuthorIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByAuthorIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByAuthorIdRequest) ProtoMessage() {}

func (x *FindByAuthorIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByAuthorIdRequest.ProtoReflect.Descriptor instead.
func (*FindByAuthorIdRequest) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{5}
}

func (x *FindByAuthorIdRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type FindByAuthorIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tours []*TourDto `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
}

func (x *FindByAuthorIdResponse) Reset() {
	*x = FindByAuthorIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByAuthorIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByAuthorIdResponse) ProtoMessage() {}

func (x *FindByAuthorIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByAuthorIdResponse.ProtoReflect.Descriptor instead.
func (*FindByAuthorIdResponse) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{6}
}

func (x *FindByAuthorIdResponse) GetTours() []*TourDto {
	if x != nil {
		return x.Tours
	}
	return nil
}

type PublishTourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourId int64 `protobuf:"varint,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
}

func (x *PublishTourRequest) Reset() {
	*x = PublishTourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTourRequest) ProtoMessage() {}

func (x *PublishTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTourRequest.ProtoReflect.Descriptor instead.
func (*PublishTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{7}
}

func (x *PublishTourRequest) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type PublishTourResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishTourResponse) Reset() {
	*x = PublishTourResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTourResponse) ProtoMessage() {}

func (x *PublishTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTourResponse.ProtoReflect.Descriptor instead.
func (*PublishTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{8}
}

type ArchiveTourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourId int64 `protobuf:"varint,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
}

func (x *ArchiveTourRequest) Reset() {
	*x = ArchiveTourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveTourRequest) ProtoMessage() {}

func (x *ArchiveTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveTourRequest.ProtoReflect.Descriptor instead.
func (*ArchiveTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{9}
}

func (x *ArchiveTourRequest) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type ArchiveTourResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ArchiveTourResponse) Reset() {
	*x = ArchiveTourResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveTourResponse) ProtoMessage() {}

func (x *ArchiveTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveTourResponse.ProtoReflect.Descriptor instead.
func (*ArchiveTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{10}
}

var File_tour_service_proto protoreflect.FileDescriptor

var file_tour_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa, 0x04, 0x0a, 0x07, 0x54, 0x6f, 0x75, 0x72, 0x44, 0x74,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x09, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63,
	0x75, 0x6c, 0x74, 0x52, 0x09, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x12, 0x1f,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x64, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x74, 0x6f, 0x52, 0x0b, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x3d, 0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x74, 0x6f, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x4c, 0x0a, 0x16, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x0e,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x41, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x44, 0x74, 0x6f, 0x52, 0x13, 0x74,
	0x72, 0x61, 0x76, 0x65, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x41, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x22, 0xc9, 0x01, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x22, 0x54,
	0x0a, 0x0c, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x74, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6d, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x54, 0x69,
	0x6d, 0x65, 0x41, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x44, 0x74, 0x6f, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x32, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x6f, 0x75, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x16,
	0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x44, 0x74, 0x6f, 0x52,
	0x05, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x22, 0x2d, 0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x6f, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74,
	0x6f, 0x75, 0x72, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x12,
	0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2a, 0x30, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05,
	0x44, 0x52, 0x41, 0x46, 0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x55, 0x42, 0x4c, 0x49,
	0x53, 0x48, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x52, 0x43, 0x48, 0x49, 0x56,
	0x45, 0x44, 0x10, 0x02, 0x2a, 0x2b, 0x0a, 0x09, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c,
	0x74, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x41, 0x53, 0x59, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d,
	0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x41, 0x52, 0x44, 0x10,
	0x02, 0x2a, 0x31, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x41, 0x52, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x49,
	0x43, 0x59, 0x43, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x4c, 0x4b, 0x49,
	0x4e, 0x47, 0x10, 0x02, 0x32, 0xc0, 0x02, 0x0a, 0x0b, 0x54, 0x6f, 0x75, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x6f, 0x75, 0x72,
	0x12, 0x10, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x08, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x47,
	0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x6f, 0x75, 0x72, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x49, 0x64, 0x12, 0x16, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x75, 0x72, 0x12, 0x08, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x44, 0x74, 0x6f, 0x1a,
	0x08, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x0a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x12, 0x08, 0x2e, 0x54, 0x6f, 0x75, 0x72,
	0x44, 0x74, 0x6f, 0x1a, 0x08, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12,
	0x3a, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x6f, 0x75, 0x72, 0x12, 0x13,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x6f, 0x75,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x12, 0x13, 0x2e, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x6f, 0x75, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tour_service_proto_rawDescOnce sync.Once
	file_tour_service_proto_rawDescData = file_tour_service_proto_rawDesc
)

func file_tour_service_proto_rawDescGZIP() []byte {
	file_tour_service_proto_rawDescOnce.Do(func() {
		file_tour_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_tour_service_proto_rawDescData)
	})
	return file_tour_service_proto_rawDescData
}

var file_tour_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tour_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tour_service_proto_goTypes = []interface{}{
	(Status)(0),                    // 0: Status
	(Difficult)(0),                 // 1: Difficult
	(TravelMethod)(0),              // 2: TravelMethod
	(*TourDto)(nil),                // 3: TourDto
	(*CheckpointDto)(nil),          // 4: CheckpointDto
	(*EquipmentDto)(nil),           // 5: EquipmentDto
	(*TravelTimeAndMethodDto)(nil), // 6: TravelTimeAndMethodDto
	(*FindTourRequest)(nil),        // 7: FindTourRequest
	(*FindByAuthorIdRequest)(nil),  // 8: FindByAuthorIdRequest
	(*FindByAuthorIdResponse)(nil), // 9: FindByAuthorIdResponse
	(*PublishTourRequest)(nil),     // 10: PublishTourRequest
	(*PublishTourResponse)(nil),    // 11: PublishTourResponse
	(*ArchiveTourRequest)(nil),     // 12: ArchiveTourRequest
	(*ArchiveTourResponse)(nil),    // 13: ArchiveTourResponse
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_tour_service_proto_depIdxs = []int32{
	1,  // 0: TourDto.difficult:type_name -> Difficult
	0,  // 1: TourDto.status:type_name -> Status
	4,  // 2: TourDto.checkpoints:type_name -> CheckpointDto
	14, // 3: TourDto.publish_time:type_name -> google.protobuf.Timestamp
	14, // 4: TourDto.archive_time:type_name -> google.protobuf.Timestamp
	5,  // 5: TourDto.equipments:type_name -> EquipmentDto
	6,  // 6: TourDto.travel_time_and_method:type_name -> TravelTimeAndMethodDto
	2,  // 7: TravelTimeAndMethodDto.travel_method:type_name -> TravelMethod
	3,  // 8: FindByAuthorIdResponse.tours:type_name -> TourDto
	7,  // 9: TourService.FindTour:input_type -> FindTourRequest
	8,  // 10: TourService.FindTourByAuthorId:input_type -> FindByAuthorIdRequest
	3,  // 11: TourService.CreateTour:input_type -> TourDto
	3,  // 12: TourService.UpdateTour:input_type -> TourDto
	10, // 13: TourService.PublishTour:input_type -> PublishTourRequest
	12, // 14: TourService.ArchiveTour:input_type -> ArchiveTourRequest
	3,  // 15: TourService.FindTour:output_type -> TourDto
	9,  // 16: TourService.FindTourByAuthorId:output_type -> FindByAuthorIdResponse
	3,  // 17: TourService.CreateTour:output_type -> TourDto
	3,  // 18: TourService.UpdateTour:output_type -> TourDto
	11, // 19: TourService.PublishTour:output_type -> PublishTourResponse
	13, // 20: TourService.ArchiveTour:output_type -> ArchiveTourResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_tour_service_proto_init() }
func file_tour_service_proto_init() {
	if File_tour_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tour_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TourDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckpointDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TravelTimeAndMethodDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindTourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByAuthorIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByAuthorIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishTourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishTourResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveTourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveTourResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tour_service_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tour_service_proto_goTypes,
		DependencyIndexes: file_tour_service_proto_depIdxs,
		EnumInfos:         file_tour_service_proto_enumTypes,
		MessageInfos:      file_tour_service_proto_msgTypes,
	}.Build()
	File_tour_service_proto = out.File
	file_tour_service_proto_rawDesc = nil
	file_tour_service_proto_goTypes = nil
	file_tour_service_proto_depIdxs = nil
}
